//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicosController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5460")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\e33230-user3\\OneDrive - hqhamamatsu.onmicrosoft.com\\デスクトップ\\PCPPC.hod")]
        public string MicosFile_Path {
            get {
                return ((string)(this["MicosFile_Path"]));
            }
            set {
                this["MicosFile_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acslaunch_win-64")]
        public string Micos_ProcessName {
            get {
                return ((string)(this["Micos_ProcessName"]));
            }
            set {
                this["Micos_ProcessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A - 5250 ディスプレイ")]
        public string Micos_WindowName {
            get {
                return ((string)(this["Micos_WindowName"]));
            }
            set {
                this["Micos_WindowName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\den3\\IC\\FROMAS400\\5460")]
        public string Micos_OutPutPath {
            get {
                return ((string)(this["Micos_OutPutPath"]));
            }
            set {
                this["Micos_OutPutPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\den0\\第2製造部\\第6・22\\製造データ\\221製造\\ASSY工程文書原稿\\ASSY図面　井上\\南雲用\\棚卸\\ラベル作成用プログラム\\ラベル紐づけテンプレ" +
            "触るな.xlsx")]
        public string ExcelLabelPath {
            get {
                return ((string)(this["ExcelLabelPath"]));
            }
            set {
                this["ExcelLabelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\den0\\第2製造部\\第6・22\\製造データ\\221製造\\ASSY工程文書原稿\\ASSY図面　井上\\南雲用\\棚卸\\ラベル作成用プログラム\\ラベル印刷テンプレ触" +
            "るな.docx")]
        public string WordLabelPath {
            get {
                return ((string)(this["WordLabelPath"]));
            }
            set {
                this["WordLabelPath"] = value;
            }
        }
    }
}
